### ISSUE TITLE
Add decorators for OpenApi - minProperties and maxProperties

### ISSUE THREAD

**Issue by jollyaakash** [microsoft/typespec#2172] opened 2023-07-11 20:01 UTC
Both [OpenApi 2.0](https://swagger.io/specification/v2/) and [OpenApi 3.0](https://swagger.io/docs/specification/data-models/data-types/) have support for adding _minProperties_ and _maxProperties_ to an restrict number of properties allowed specially in case of free-form objects/additionalProperties.

It would be good to have a decorator maybe like for an object model-

@minProperties() 
@maxProperties()

**Comment by jollyaakash** [comment] 2023-07-11 20:01
cc: @varunpuranik

**Comment by bterlson** [comment] 2023-07-11 20:53
These are supported in the json-schema emitter. Perhaps we can consider adding these to core.

**Comment by jollyaakash** [comment] 2023-07-17 17:05
@bterlson can both emitters work together ? 

- '@azure-tools/typespec-autorest'
- '@typespec/json-schema'

**Comment by markcowl** [comment] 2023-07-17 18:49
Closing as duplicate of #1060

@bterlson OpenAPI uses a lot of json schema, I wonder if we shouldn't have a dependency on the json schema library in the openapi libraries

**Closed** 2023-07-17 18:49 UTC
Labels: needs-triage
