### ISSUE TITLE
Missing meta properties of ModelProperty

### ISSUE THREAD

**Issue by johanste** [microsoft/typespec#2522] opened 2023-10-01 19:55 UTC
```typespec
model ThingWithNested {
  nested: {
    name: string;
  }
}

model Spreaddie {
  ...ThingWithNested;
}

@@doc(Spreaddie.nested::type, "Yeaj");
```

> error
invalid-ref
ModelProperty doesn't have meta property type

[Playground](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgVGhpbmdXaXRoTmVzdGVkIHsKICBuxQs6xQwgIG5hbWU6IHN0cmluZzsKICB9Cn0KCsY9U3ByZWFkZGllxSsuLi7PTjvEK0BAZG9jKMkrLsdeOnR5cGUsICJZZWFqIik7&e=%40typespec%2Fopenapi3&options=%7B%7D)

The list of meta properties seem to be... lacking...

**Comment by daviwil** [comment] 2023-10-02 07:19
I believe this is a dupe of another issue I filed: https://github.com/microsoft/typespec/issues/2213

**Comment by markcowl** [comment] 2023-10-10 00:31
Closing as duplicate of #2213

**Closed by markcowl** 2023-10-10 00:31 UTC
Labels: needs-triage
