### ISSUE TITLE
Decorator @doc is not working on adding descriptions to Responses

### ISSUE THREAD

**Issue by norelina** [microsoft/typespec#2346] opened 2023-08-31 14:21 UTC
Decorator @doc is not working as expected in setting the description property for Responses. 

<img width="924" alt="image" src="https://github.com/microsoft/typespec/assets/54459761/86a1e07f-51ef-43a2-90a2-d7045ae2ec11">

Documentation reference: https://microsoft.github.io/typespec/getting-started/typespec-for-openapi-dev#response-object

**Comment by mikekistler** [comment] 2023-08-31 14:33
I think your `@doc` is in the wrong place -- it needs to go on the model rather than the status code.

See the [Response Object](https://github.com/mikekistler/typespec-openapiv3-examples/blob/main/README.md#response-object) section of my examples repo and the corresponding playground.

**Comment by norelina** [comment] 2023-08-31 14:48
@mikekistler thank you for your response. I have updated the screenshot to correctly demonstrate the issue.

**Comment by norelina** [comment] 2023-08-31 14:59
@mikekistler in addition of getting the @doc decorator set the Response description, a desired outcome is to be able to customize the description of an error message without setting a `@body`. E.g., 
<img width="289" alt="image" src="https://github.com/microsoft/typespec/assets/54459761/a5ee2249-2997-41ee-97de-4b6c700d7aa4">
Is this possible?

**Comment by mikekistler** [comment] 2023-08-31 15:14
See [this playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7CtIZb3BlbmFwaTMiOwovL8gfIC4vc2NoZW1hcyAudHNwIjsKCnVzaW5nIFR5cGVTcGVjLkh0dHA7CgpAc2VydmljZSh7CiAgdGl0bGU6ICLIJSAtIFBldCBTxiMiLAogIHZlcnNpb246ICIwLjEuMCIsCn0pCm5hbWVzcGFjZSBNYWRlLkFwaTsKCm1vZGVsxUB7fQoKQGRvYygiUGV0cyByZXRyaWV2ZWQgc3VjY2Vzc2Z1bGx5IinKMkxpc3Qg5ACRQHN0YXR1c0NvZGUgXzogIjIwMCI7xBhib2R5IMQFOsQwW107Cn3kAM1kb2MgKCJUaGlzIGlzIGEgY3VzdG9tIHVuYXV0aG9yaXplZCByZXNwb25zZclxQ8UlVcskUscj9QCENDAxIjsKfQoKCkByb3V0ZSAoIi9hcGkvcGV0cyIpCkB0YWcg5gDqIikKaW50ZXJm5AEaxBFJyQ7FWWdldCBsaXN0KCnlAMblAPZ8%2BwCP5AD6Ly9AcG9zdCBjcmVhxHwuLi5QZXQpOiAoQ8USyS0gJsRUKcRRxRlSZXR1cm7kAdpzxnrEBChAcGF0aCBpZDogc3RyaW5n5gCKIHwgUmVhZMszyHt1dCB1cGRhdGXKecYwVcUWzzJAZGVsZXRlIMYH1G12b2lkOwp9&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by norelina** [comment] 2023-08-31 15:51
@mikekistler thank you for sharing this. We are hoping that we can have different operations that all return the same schema (JSON object) but provide different descriptions for each of those responses. 

Essentially, we want to set the response description, not the model description so that we don't have to create different schemas for each response. 

<img width="327" alt="image" src="https://github.com/microsoft/typespec/assets/54459761/25180d65-676f-4514-8e6c-1c65bb1849d8">


Is there a way to support this with TypeSpec?

**Comment by mikekistler** [comment] 2023-08-31 16:20
I don't think you can attach decorators like @doc to a model expression -- it needs to be a named model. Sorry.

**Comment by tvenhaus** [comment] 2023-08-31 17:12
Mike - we would like to specify response descriptions **without creating a new model** for each operation.  It looks like this should be possible according to [this documentation](https://microsoft.github.io/typespec/getting-started/typespec-for-openapi-dev#response-object).

Specifically, this example from the documentation:
![image](https://github.com/microsoft/typespec/assets/13563386/79e6b8b4-0f8e-4704-8820-bfa338ed181c)

We have tried to explain this better in [this playground.](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7CtIZb3BlbmFwaTMiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDsKCkBzZXJ2aWNlKHsKICB0aXRsZTogIsglIC0gUGV0cyBTxiQiLAogIHZlcnNpb246ICIwLjEuMCIsCn0pCm5hbWVzcGFjZSBTYW1wbGUuxDc7Cgptb2RlbMREIMRfICBAcGF0aMUKaWQ6IHN0cmluZzvFEMRCyhJ9CgpAZG9jKCLEO3JldHJpZXZlZCBzdWNjZXNzZnVsbHkiKcpeR8dhQHN0YXR1c0NvZGUgXzogIjIwMCLEX0Bib2R5IMQFOsQvOwp95AD6yWF1cGRhdNtfVcUg32LUYnJvdXRlKCIvYXBpL3BldHMiKQpAdGFnxXbEDWludGVyZuQBN1BldEnJDcRpLy8gV2hpbGUgdGhpc%2BcAonMgdGhlIHJlc3BvbnNlIGRlc2NyaXB0aW9ucywgaXQgaXMgbm90IGlkZWFsxkNiZWNhdXNlIHdlIGhhdmUgdG8gY3Jl5ADNYSBuZXcg5gDjZm9yIGV2ZXJ5IOQCI2xlxjxvcGVyYcRd5AJfxnIoaS5lLiDkAL5HZXQiIGFuZMUN5gEgIikK5AEJZ2V0IGdldCjlAevrAecp5QEZ5AGqfCBOb3RGb3VuZFLHWTvFOnB16AGLKC4u5AJCxjPGXtU2ICDlAirwAWcy7QFoxA7tAWky8QFqVOQBZGlzIHdoYXTkASx3b3VsZCBleHBlY3TkATR3b3JrIGJhc2VkIG9u5QGFZG9jdW1lbnTlASHGRcca6ACeIE9iasQ%2FLSDGH2h0dHBzOi8vbWljcm9zb2Z0LmdpdGh1Yi5pby%2FpA7BnZXR0aW5nLXN0YXJ0ZWTJGS1mb3It5wPNLWRldiPoAZMtb8VmxWPGaE5vdOQCNWF05gI6ZXjlA5EgYWxz6AH8cyBhIHNjaGVtYeUB%2Bu0EEi7wAWUsIHdoaWNoIGlzx19PVOQCeWlyZWQuICBJbnN0ZWFkLOQBNWp1c3Qgd2Fu5QEyYmUgYWLkAr5vIOQAwGlmeeUBHeQDdOUCN%2BYDMFdJVEhPVVQgaeYAweYAoOQEpugAoS7%2FAlPoBFf%2FBCwiKcYnxHXFCnBldOUCXAogIH0gfNFGd2l0aOcAuGllZCBpZOUDWGbkARjRS27nATE68QKgxF36AtrQdPcEhf8AuP8AuP8AuPwAuOQDXA%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by markcowl** [comment] 2023-09-06 19:18
Closing as duplicate of https://github.com/microsoft/typespec/issues/2185

**Closed by markcowl** 2023-09-06 19:18 UTC
Labels: needs-triage
