### ISSUE TITLE
[Bug]: @server decorator failed to generate without description.

### ISSUE THREAD

**Issue by skywing918** [microsoft/typespec#3924] opened 2024-07-22 07:58 UTC
### Describe the bug

@server decorator failed to generate without description..
## TSP
```
import "@typespec/http";
import "@typespec/openapi3";

using TypeSpec.Http;
using TypeSpec.OpenAPI;
@service
@server("https://test.contoso.com")
namespace PetStore;
```
## Actual Specification
![image](https://github.com/user-attachments/assets/671fde6c-3f22-47eb-8e1b-647211922234)
``` yaml
@server("https://test.contoso.com", "test domain")
``` 
## Expected Specification
https://spec.openapis.org/oas/v3.0.0#server-object
![image](https://github.com/user-attachments/assets/722ba972-670f-4f37-b9f5-87e3ecccc949)

the field description is not required.
``` yaml
url: "https://test.contoso.com"
``` 

### Reproduction

1. `git clone https://github.com/skywing918/typespec-workaround.git`
2. `tsp compile server.tsp`
3. Open `/tsp-output/@typespec/openapi3` to get the result

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment] 2024-07-22 15:05
Duplicate of https://github.com/microsoft/typespec/issues/2229

**Closed by timotheeguerin** 2024-07-22 15:05 UTC
Labels: bug, needs-area
