### ISSUE TITLE
Payload examples for OAS

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/typespec#2087] opened 2023-06-17 14:05 UTC
### Discussed in https://github.com/microsoft/typespec/discussions/2047

---

OAS 3 provides the ability to specify examples for object schemas and payloads. Currently TypeSpec does not support this feature but it is fairly important to communicate how any API can be used.

I propose that an `@example` decorator could be added to support this. Ideally multiple examples could be added.

For example:

```typespec
@example({id: "test", weight: 12, color: "blue"})
@example({id: "test2", weight: 50, color: "red"})
model Widget {
  @visibility("read", "update")
  @path
  id: string;
  weight: int32;
  color: "red" | "blue";
}

@error
model Error {
  code: int32;
  message: string;
}

@route("/widgets")
@tag("Widgets")
interface Widgets {
  @get read(@path id: string): Widget | Error;
}
```

Which would result in:

```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "(title)",
    "version": "0000-00-00"
  },
  "tags": [
    {
      "name": "Widgets"
    }
  ],
  "paths": {
    "/widgets/{id}": {
      "get": {
        "tags": [
          "Widgets"
        ],
        "operationId": "Widgets_read",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The request has succeeded.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Widget"
                }
              }
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Error": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32"
          },
          "message": {
            "type": "string"
          }
        },
        "required": [
          "code",
          "message"
        ]
      },
      "Widget": {
        "type": "object",
        "example": [
          {
            "id": "test",
            "weight": 12,
            "color": "blue"
          },
          {
            "id": "test2",
            "weight": 50,
            "color": "red"
          }
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "weight": {
            "type": "integer",
            "format": "int32"
          },
          "color": {
            "type": "string",
            "enum": [
              "red",
              "blue"
            ],
            "x-typespec-name": "red | blue"
          }
        },
        "required": [
          "id",
          "weight",
          "color"
        ]
      }
    }
  }
}
```

**Comment by markcowl** [comment] 2023-06-23 17:14
@markcowl: find duplicate

**Comment by decarufe** [comment] 2023-07-26 14:28
@markcowl & @BernieWhite I think it would be really nice to support "examples" for specific request and response. I use [Specmatic](https://specmatic.in/getting_started.html#api-specification) to test my OpenAPI contract and it relies on those examples for stubs and server tests.

**Comment by FH-Inway** [comment] 2023-07-29 16:06
@markcowl This may be the duplicate you are looking for: #514

**Comment by markcowl** [comment] 2023-08-09 22:48
closing as duplicate of #514   Particularly, the proposal: https://gist.github.com/markcowl/a45d32be8d2f25c87df196672605415c

**Closed** 2023-08-09 22:48 UTC
Labels: needs-triage
