### ISSUE TITLE
[Bug]: Doc comments are cut off at inline tags

### ISSUE THREAD

**Issue by rmhartog** [microsoft/typespec#3374] opened 2024-05-16 10:07 UTC
### Describe the bug

When using doc comments (TSDoc syntax), inline tags such as `{@link}` or any other text containing an `@`-symbol cause the description to be cut off at the `@`-symbol.

### Reproduction

[Reproduction in Playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CnVzaW5nIFR5cGVTcGVjLkh0dHA7CgovKioKICogRXhhbXBsZSBvZiBhIGRlc2NyaXB0aW9uIHtAbGluayDERHM6Ly9naXRodWIuY29tL21pY3Jvc29mdC90c2RvY33ER1NvbWUgbW9yZSB0ZXh0IGhlcmUKICovCkBzZXJ2aWNlKCkKbmFtZXNwYWNlIFPGFDs%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)

The following example

```
import "@typespec/http";
using TypeSpec.Http;

/**
 * Example of a description {@link https://github.com/microsoft/tsdoc}
 * Some more text here
 */
@service()
namespace Service;
```

results in the following OpenAPI output

```yml
openapi: 3.0.0
info:
  title: (title)
  description: Example of a description {
  version: 0.0.0
tags: []
paths: {}
components: {}
```

The same applies for any other text containing an `@`-symbol, like email-adresses, unless escaped with backticks.

I'm not sure to what extent TSDoc compatibility is a goal, but I've noticed tags like `@param` are supported, so I imagine this is a issue.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment] 2024-05-16 14:51
we do not support that syntax just yet but it is on our plans, see this issue https://github.com/microsoft/typespec/issues/1358

**Comment by markcowl** [comment] 2024-05-20 18:27
Closing as duplicate of: https://github.com/microsoft/typespec/issues/1358

**Closed by markcowl** 2024-05-20 18:27 UTC
Labels: bug, needs-area
