### ISSUE TITLE
Type checking against anonymous model types produces vague errors

### ISSUE THREAD

**Issue by daviwil** [microsoft/typespec#1832] opened 2023-04-18 14:23 UTC
When you use a decorator that has an anonymous object shape as one of its parameter types, the error produced by the compiler makes it very unclear what went wrong.  For example:

```
import "@typespec/http";
using TypeSpec.Http;

@route("foo", { shared: "foo" })
op go(): {};
```

[Playground](https://cadlplayground.z22.web.core.windows.net/prs/1798/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CnVzaW5nIFR5cGVTcGVjLkh0dHA7CgpAcm91dGUoImZvbyIsIHsgc2hhcmVkOiDFESB9KQpvcCBnbygpOiB7fTs%3D)

The error returned is:

```
error invalid-argument: Argument '(anonymous model)' is not assignable to parameter of type '(anonymous model)'
```

It'd be nice if it could print out the expected shape at least so that the user has a lead on what they need to fix.

**Comment by timotheeguerin** [comment] 2023-04-18 15:38
I think this is a sub issue in this bigger problem #1823

**Comment by markcowl** [comment] 2023-04-18 18:47
Closing as duplicate of #1823

**Closed by markcowl** 2023-04-18 18:47 UTC
Labels: Needs Triage
