### ISSUE TITLE
[Bug?] Multiline doc comments newlines

### ISSUE THREAD

**Issue by connorjs** [microsoft/typespec#2389] opened 2023-09-09 19:49 UTC
### TL;DR

Multiline comments currently emit a double newline in the Open API 3 YAML. Instead, it should preserve the doc comment exactly as is, minus the leading `*` when using the doc comment form.

### Overview

Support emitting multiline doc comment "correctly" (as expected by `/**` TypeDoc/TSDoc/JSDoc conventions).

### Current state

```
/**
 * My multiline
 * doc comment.
 */
```

becomes

```yml
description: >-
  My multiline

  doc comment.
```

### Expected state

I would expect it to become this instead.

```yml
description: >-
  My multiline
  doc comment.
```

Note the single newline (no blank line).

**Comment by markcowl** [comment] 2023-09-11 18:11
closing as duplicate of #2350

**Closed by markcowl** 2023-09-11 18:11 UTC
Labels: customer-reported, needs-triage

**Comment by connorjs** [comment] 2023-09-11 21:29
Thanks all!
