### ISSUE TITLE
[Bug]: There is no way to set the description for OpenAPI responses openapi-emitter [emitter:openapi3]

### ISSUE THREAD

**Issue by AngelEVargas** [microsoft/typespec#4242] opened 2024-08-22 17:21 UTC
### Describe the bug

Documentation strings added to the TypeSpec model or attributes of the response are not reflected in the generated OpenAPI responses description.  Instead, the descriptions added by the emitter are some standard ones.
```
@doc("How to replace standard description with this one?")
model NotAuthenticatedError extends Errors.Error {
  @doc("Or maybe with this other?")
  @statusCode
  _: 401
}
```
Generates:
```
       '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotAuthenticatedError'
```

cc @mario-guerra 

### Reproduction

[Playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZb3BlbmFwaTMiOwp1c2luZyBIdHRwyAxUeXBlU3BlYy5PcGVuQVBJOwpAc2VydmljZQpuYW1lc3BhY2UgdGVzdDsKCkBkb2MoIkhvdyB0byByZXBsxBxzdGFuZGFyZCBkZXNjcmlwdGlvbiB3aXRoIHRoaXMgb25lPyIpCkBlcnJvcgptb2RlbCBNeVVuYXV0aGVudGljYXRlZEXEHSB7CiAgY29kZTogaW50MzI7CiAgbWVzc2FnZTogc3RyaW5nxBPmAIVPciBtYXliZcxqdGhlcsRsICBAc3RhdHVzQ29kZQogIF86IDQwMQp9CgppbnRlcmbkALZNeUnJDMR4b3AgTXlPcCgpOiAvKsZjVMRVaXMgbm90IGFsbG93ZWQiKSov9wC%2BCn0K&e=%40typespec%2Fopenapi3&options=%7B%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mario-guerra** [comment] 2024-08-22 21:41
@timotheeguerin is it possible to override the default operation description?

**Comment by chrisradek** [comment] 2024-08-22 22:12
I believe this is a duplicate of #3664 which is also marked as a bug.

Currently you'd need either an empty model, or explicitly define the body/bodyRoot parameter like this: [playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZb3BlbmFwaTMiOwp1c2luZyBIdHRwyAxUeXBlU3BlYy5PcGVuQVBJOwpAc2VydmljZQpuYW1lc3BhY2UgdGVzdDsKCkBlcnJvcgptb2RlbCBNeVVuYXV0aGVudGljYXRlZEXEHSB7CiAgY29kZTogaW50MzI7CiAgbWVzc2FnZTogc3RyaW5nxBNAc3RhdHVzQ29kZQogIF86IDQwMQp9CgpAZG9jKCJIb3cgdG8gcmVwbMR%2Bc3RhbmRhcmQgZGVzY3JpcHRpb24gd2l0aCB0aGlzIG9uZT8iKfAAnU9wUmVzcG9uc2XlAJNAYm9keVJvb3QgcscXOvcAwuQAh2ludGVyZsR8TXlJyQzESG9wxVwoKcQ%2FymQKfQo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by AngelEVargas** [comment] 2024-08-26 17:41
Thank you @chrisradek that is helpful

**Comment by mario-guerra** [comment] 2024-08-26 17:56
@AngelEVargas closing this issue as a duplicate.

**Closed by mario-guerra** 2024-08-26 17:56 UTC
Labels: bug, needs-area
