### ISSUE TITLE
[Bug]: @example decorator on operation parameter does not generate example in OpenApi parameter specification

### ISSUE THREAD

**Issue by gdahlin** [microsoft/typespec#4942] opened 2024-11-01 13:40 UTC
### Describe the bug

The `@typespec/openapi3` emitter supports `@example` for models, but does not output example when models are used as header params.

Example
```
@example(#{token: "Bearer YOUR_TOKEN_HERE"})
model headers {
  @header("Authorization") token: authToken
}

@example("Bearer SOME_TOKEN")
scalar authToken extends string;

@get
op someop(...headers) : void;
```

Would ideally output:

```
openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths:
  /:
    get:
      operationId: someop
      parameters:
        - $ref: '#/components/parameters/headers'
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
components:
  parameters:
    headers:
      name: Authorization
      in: header
      required: true
      example: Bearer YOUR_TOKEN_HERE
      schema:
        $ref: '#/components/schemas/authToken'
  schemas:
    authToken:
      type: string
      example: Bearer SOME_TOKEN
```

Although, the header parameter example is not generated, only the schema example.

### Reproduction

https://[typespec.io/playground/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBIdHRwOwoKQGV4YW1wbGUoI3t0b2tlbjogIkJlYXJlciBZT1VSX1RPS0VOX0hFUkUifSkKbW9kZWwgaGVhZGVycyB7CiAgQMYNKCJBdXRob3JpemF0aW9uIikgx01hdXRoVMQLCn3LbMhjU09NRcZjIikKc2NhbGFyyjIgZXh0ZW5kcyBzdHJpbmfkAKxnZXQKb3Agc29tZW9wKC4uLsZ%2BcykgOiB2b2lkOw%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D](https://typespec.io/playground/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBIdHRwOwoKQGV4YW1wbGUoI3t0b2tlbjogIkJlYXJlciBZT1VSX1RPS0VOX0hFUkUifSkKbW9kZWwgaGVhZGVycyB7CiAgQMYNKCJBdXRob3JpemF0aW9uIikgx01hdXRoVMQLCn3LbMhjU09NRcZjIikKc2NhbGFyyjIgZXh0ZW5kcyBzdHJpbmfkAKxnZXQKb3Agc29tZW9wKC4uLsZ%2BcykgOiB2b2lkOw%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment] 2024-11-01 14:04
duplicate of https://github.com/microsoft/typespec/issues/3873

**Closed by timotheeguerin** 2024-11-01 14:04 UTC
Labels: bug, needs-area
