### ISSUE TITLE
Warning "@versionedDependency is deprecated" is repeated 3 times

### ISSUE THREAD

**Issue by mikeharder** [microsoft/typespec#1782] opened 2023-04-03 22:46 UTC
## Repro Steps
1. Create a `main.tsp` with an `@versionedDependency`:

```
@versionedDependency(
  [[Mharder.Test.Versions.`2022-11-01-preview`, Azure.Core.Versions.v1_0_Preview_1]]
)
```

2. Run `tsp compile .`

## Expected
One warning

## Actual
The same warning is repeated 3 times:

```
/home/mharder/azure-rest-api-specs-mh/specification/mhardertest/Mharder.Test/main.tsp:14:1 - warning deprecated: Deprecated: @versionedDependency is deprecated. Use @useDependency instead.
> 14 | @versionedDependency(
     | ^^^^^^^^^^^^^^^^^^^^^
> 15 |   [[Mharder.Test.Versions.`2022-11-01-preview`, Azure.Core.Versions.v1_0_Preview_1]]
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 16 | )
     | ^^
/home/mharder/azure-rest-api-specs-mh/specification/mhardertest/Mharder.Test/main.tsp:14:1 - warning deprecated: Deprecated: @versionedDependency is deprecated. Use @useDependency instead.
> 14 | @versionedDependency(
     | ^^^^^^^^^^^^^^^^^^^^^
> 15 |   [[Mharder.Test.Versions.`2022-11-01-preview`, Azure.Core.Versions.v1_0_Preview_1]]
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 16 | )
     | ^^
/home/mharder/azure-rest-api-specs-mh/specification/mhardertest/Mharder.Test/main.tsp:14:1 - warning deprecated: Deprecated: @versionedDependency is deprecated. Use @useDependency instead.
> 14 | @versionedDependency(
     | ^^^^^^^^^^^^^^^^^^^^^
> 15 |   [[Mharder.Test.Versions.`2022-11-01-preview`, Azure.Core.Versions.v1_0_Preview_1]]
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 16 | )
     | ^^
```

**Comment by timotheeguerin** [comment] 2023-04-03 22:49
The problem I think is the versionedDependency decorator is calling `reportDeprecated` but its also being called for each of the projected versions.

**Comment by markcowl** [comment] 2023-04-04 19:02
CLosing as duplicate of #1166

**Comment by markcowl** [comment] 2023-05-03 18:55
- come up with mechanism for reporting decorator deprecation

**Comment by markcowl** [comment] 2023-05-03 19:18
This should be resolved by this issue: https://github.com/microsoft/typespec/issues/1166  Closing a s duplicate

**Closed by markcowl** 2023-05-03 19:18 UTC
Labels: TypeSpec Design
