### ISSUE TITLE
Support cadl install from package-lock.json

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#1654] opened 2023-02-16 20:54 UTC
We need a way to do an install of a cadl project that uses package-lock.json rather than package.json, for reproducible builds. npm provides `npm ci` for this. We could add the equivalent support to the cadl command or we could make `npm ci` the accepted way to do this (which would still involve documentation updates).

**Comment by markcowl** [comment] 2023-02-21 19:57
document how to use package-lock with npm

**Comment by markcowl** [comment] 2023-02-21 19:57
est: 1

**Comment by markcowl** [comment] 2023-04-05 23:16
Closing as duplicate of https://github.com/Azure/typespec-azure/issues/2267

**Closed by markcowl** 2023-04-05 23:16 UTC
Labels: documentation, :pushpin:, WS: Svc Partner Adoption
