### ISSUE TITLE
projectedName does not work when using the @versioned decorator

### ISSUE THREAD

**Issue by glecaros** [microsoft/typespec#1696] opened 2023-03-08 22:18 UTC
The `@projectedName` attribute works properly for the `@azure-tools/typespec-autorest` emitter normally, but when I add `@versioned` to the service the output shows with the unmodified name.  Attached is a small repro of the problem.

[projectedName.tar.gz](https://github.com/microsoft/typespec/files/10925677/projectedName.tar.gz)

**Comment by markcowl** [comment] 2023-03-15 16:45
@markcowl look for duplicate issue

**Comment by markcowl** [comment] 2023-03-15 18:41
Closing as duplicate of #2623

**Closed by markcowl** 2023-03-15 18:41 UTC
Labels: Needs Triage
